### PR TITLE
Revert 3.4 change to ruby predicate method names (fixes #31)

### LINKED ISSUE #31: Revert 3.4 change to ruby method names
Per [this discussion thread](https://groups.google.com/forum/#!topic/vertx/CdH7AZDLvR0), ruby predicate method names were changed in version 3.4 to only end with a question mark if the method name begins with "is".  

However, it is definitely idiomatic in ruby that *all* predicate method names should end with a question mark.  This is true for core ruby (e.g., [Object](https://ruby-doc.org/core-2.3.3/Object.html)), the standard library, and 3rd party libraries/gems.

Please restore the idiomatic behavior in version 3.5.

### PR DESCRIPTION
**Pull request by mmindenhall**
Submitting PR for this as requested.  Thanks!

### CODE REVIEW

**Comment by tsegismont** [comment]
Thanks! Looks good to me. Can you please send an email to vertx-dev? This would be a breaking change so it should be advertised there.

**Comment by mmindenhall** [comment]
I've posted twice in the vertx-dev google group, but neither post has shown up in the list.  Is there a moderator that needs to approve?

**Comment by mmindenhall** [comment]
@tsegismont, would you mind posting the following?  I've tried posting to the vertx-dev google group twice, and both times it looks like the post succeeds, but then it never appears.  This has happened to me before also on the vertx-user group...I post something and it never shows in the list.  Is there a moderator rejecting these posts?

---
Subject: Proposed breaking change in 3.5 (vertx-lang-ruby)
Hello,

In vert.x 3.4, there was a breaking change to ruby predicate method names ([vertx-lang-ruby commit](https://github.com/vert-x3/vertx-lang-ruby/commit/ff619130c3e7cc2abf6a528752056672b1c74191)):

> only append "?" if the method returns boolean and is prefixed by "is", e.g isComplete()


Although that was a breaking change, it somehow slipped through the cracks and was not called out in the 3.4 release notes.

It is idiomatic in ruby that all predicate method names should end with a question mark. This is true for core ruby (e.g., [Object](https://ruby-doc.org/core-2.3.3/Object.html)), the standard library, and 3rd party libraries/gems.  For that reason, I filed an [issue](https://github.com/vert-x3/vertx-lang-ruby/issues/31), which was followed up with [a pull request](https://github.com/vert-x3/vertx-lang-ruby/pull/32).  The change simply reverts the non-idiomatic predicate method names introduced in the 3.4 release.  Since this is also a breaking change (against 3.4.x only), Thomas Segismont asked me to post here.

If the PR is accepted, this will need to be called out in the release notes for 3.5.

Thanks!

--Mark

**Comment by tsegismont** [comment]
Sure, will do.

2017-09-15 22:00 GMT+02:00 Mark Mindenhall <notifications@github.com>:

**Comment by tsegismont** [comment]
@mmindenhall thank you!

**Comment by tsegismont** [comment]
I updated the 3.5 breaking changes page.

2017-09-16 13:56 GMT+02:00 Julien Ponge <notifications@github.com>:

**Pull request merged**
